// 'freeUitilities',
// 'dogsAllowed',
// 'catsAllowed',
// 'improvedSecurity',
// 'improvedParking',

const configUpgrades = {
  "swimmingPool": {
    "name": "Swimming pool",
    "desc": "This is a pool",
    "cost": 15000,
    "monthlyCostPerResident": 80,
    "instantHappiness": 25,
    "monthlyProfitPerResident": 0,
  },
  "freeUitilities": {
    "name": "Free Utilities",
    "desc": "Is it really free if the landlord pays for it?",
    "cost": 0,
    "monthlyCostPerResident": 100,
    "instantHappiness": 25,
    "monthlyProfitPerResident": 0,
  },
  "dogsAllowed": {
    "name": "Dogs are allowed",
    "desc": "Puppers be free",
    "cost": 0,
    "monthlyCostPerResident": 0,
    "instantHappiness": 10,
    "monthlyProfitPerResident": 10,
  },
  "catsAllowed": {
    "name": "Cats are allowed",
    "desc": "Our properties are purrfect",
    "cost": 0,
    "monthlyCostPerResident": 0,
    "instantHappiness": 10,
    "monthlyProfitPerResident": 6,
  },
  "improvedSecurity": {
    "name": "Improved security",
    "desc": "Keep your residents safe, and YOUR money safer",
    "cost": 15000,
    "monthlyCostPerResident": 30,
    "instantHappiness": 10,
    "monthlyProfitPerResident": 0,
  },
  // "improvedParking": {
  //   "name": "Swimming pool",
  //   "desc": "This is a pool",
  //   "cost": 10000,
  //   "monthlyCostPerResident": 250,
  //   "instantHappiness": 25,
  //   "monthlyProfitPerResident": 0,
  // },
};
