// 'freeUitilities',
// 'dogsAllowed',
// 'catsAllowed',
// 'improvedSecurity',
// 'improvedParking',

const configUpgrades = {
  "swimmingPool": {
    "name": "Swimming pool",
    "desc": "This is a pool",
    "cost": 10000,
    "monthlyCostPerResident": 250,
    "instantHappiness": 25,
    "happinessModifier": 1.008,
    "monthlyProfitPerResident": 0,
  },
  "freeUitilities": {
    "name": "Free Utilities",
    "desc": "Is it really free the landlord pays for it?",
    "cost": 0,
    "monthlyCostPerResident": 1000,
    "instantHappiness": 25,
    "happinessModifier": 1.01,
    "monthlyProfitPerResident": 0,
  },
  "dogsAllowed": {
    "name": "Dogs are allowed",
    "desc": "Puppers be free",
    "cost": 0,
    "monthlyCostPerResident": 0,
    "instantHappiness": 10,
    "happinessModifier": 1.0005,
    "monthlyProfitPerResident": 10,
  },
  "catsAllowed": {
    "name": "Swimming pool",
    "desc": "This is a pool",
    "cost": 10000,
    "monthlyCostPerResident": 250,
    "instantHappiness": 25,
    "happinessModifier": 1.00,
    "monthlyProfitPerResident": 0,
  },
  "improvedSecurity": {
    "name": "Swimming pool",
    "desc": "This is a pool",
    "cost": 10000,
    "monthlyCostPerResident": 250,
    "instantHappiness": 25,
    "happinessModifier": 1.00,
    "monthlyProfitPerResident": 0,
  },
  "improvedParking": {
    "name": "Swimming pool",
    "desc": "This is a pool",
    "cost": 10000,
    "monthlyCostPerResident": 250,
    "instantHappiness": 25,
    "happinessModifier": 1.00,
    "monthlyProfitPerResident": 0,
  },
};
